name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # =========================
  # 1️⃣ Semgrep Security Scan
  # =========================
  semgrep:
    runs-on: ubuntu-latest
    outputs:
      semgrep-pass: ${{ steps.semgrep-pass.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Semgrep
        run: pip install semgrep==1.144.0

      - name: Run Semgrep and fail on ERROR
        id: semgrep-pass
        run: |
          echo "Running Semgrep scan..."
          semgrep --config .semgrep.yml \
                  --exclude node_modules \
                  --exclude target \
                  --json --quiet --skip-unknown-extensions > semgrep-results.json

          echo "Scan complete. Parsing results for ERROR severity..."
          jq '.results[] | {check_id: .check_id, path: .path, start: .start, severity: .extra.severity, message: .extra.message}' semgrep-results.json

          if jq '.results[] | select(.extra.severity=="ERROR")' semgrep-results.json | grep -q '.'; then
            echo "ERROR severity findings detected. Failing CI."
            cat semgrep-results.json | jq '.results[] | select(.extra.severity=="ERROR")'
            exit 1
          else
            echo "No ERROR severity findings. CI passes."
            echo "result=true" >> $GITHUB_OUTPUT
          fi



  build-and-push:
    runs-on: ubuntu-latest
    needs: semgrep
    if: ${{ needs.semgrep.outputs.semgrep-pass == 'true' }}
    steps:
      - uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME="ghcr.io/$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')/icm-server:latest"
          docker build -t $IMAGE_NAME .

      # Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_NAME="ghcr.io/$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')/icm-server:latest"
          docker push $IMAGE_NAME
